"""Navigation presentation helpers."""

from .map_presenter import (
    center_view_on_global_position,
    create_initial_hint_marker,
    create_last_position_marker,
    create_map_scene_items,
    hide_item,
    set_target_marker,
    update_game_view_rect_item,
    update_localization_view,
    update_monitor_rect_item,
    update_player_marker,
)
from .status_presenter import (
    append_navigation_status_suffix,
    build_navigation_status_text,
    show_navigation_arrived,
    show_navigation_failed,
    show_navigation_relocalizing,
    show_navigation_runtime_status,
)
from .event_overlay import clear_event_overlay, global_to_scene, render_event_overlay
from .route_overlay import clear_route_overlay, render_route_overlay
from .viewport_overlay import screen_overlay_geometry
from .dialog_host import show_owned_dialog, toggle_owned_dialog
from .debug_overlay import update_debug_overlay
from .map_load_state import (
    apply_map_loaded_ui,
    populate_map_combo,
    show_map_load_failed,
    warn_map_config_missing,
    warn_overlay_map_config_incomplete,
)
from .config_save_state import (
    mark_nav_params_dirty,
    show_default_nav_config_save_failed,
    show_default_nav_config_saved,
    show_nav_config_save_failed,
    show_nav_config_saved,
    warn_default_nav_config_missing,
    warn_nav_config_missing_map,
)
from .calibration_feedback import (
    show_hint_mode_status,
    show_initial_hint_set,
    show_screen_center_calibrated,
)
from .event_management_state import (
    show_event_config_save_failed,
    show_event_config_saved,
    show_event_state_reset,
    show_portal_event_state_reset,
    show_portal_manual_test_started,
    show_portal_manual_test_stopped,
    warn_event_config_missing,
    warn_event_system_missing,
    warn_portal_manual_test_missing_screen_center,
)
from .navigation_command_state import (
    show_auto_navigation_started,
    show_auto_navigation_stopped,
    show_navigation_paused,
    show_navigation_started,
    warn_auto_navigation_invalid_route,
    warn_auto_navigation_unavailable,
    warn_navigation_map_config_incomplete,
    warn_navigation_missing_screen_center,
)
from .route_command_state import (
    show_move_target_set,
    show_route_command_status,
    warn_move_target_requires_localization,
    warn_route_save_failed,
)

__all__ = [
    "apply_map_loaded_ui",
    "append_navigation_status_suffix",
    "build_navigation_status_text",
    "center_view_on_global_position",
    "clear_event_overlay",
    "clear_route_overlay",
    "create_initial_hint_marker",
    "create_last_position_marker",
    "create_map_scene_items",
    "global_to_scene",
    "hide_item",
    "mark_nav_params_dirty",
    "populate_map_combo",
    "render_event_overlay",
    "render_route_overlay",
    "screen_overlay_geometry",
    "set_target_marker",
    "show_default_nav_config_save_failed",
    "show_default_nav_config_saved",
    "show_event_config_save_failed",
    "show_event_config_saved",
    "show_event_state_reset",
    "show_hint_mode_status",
    "show_initial_hint_set",
    "show_map_load_failed",
    "show_nav_config_save_failed",
    "show_nav_config_saved",
    "show_auto_navigation_started",
    "show_auto_navigation_stopped",
    "show_navigation_paused",
    "show_navigation_arrived",
    "show_navigation_failed",
    "show_navigation_relocalizing",
    "show_navigation_runtime_status",
    "show_navigation_started",
    "show_move_target_set",
    "show_owned_dialog",
    "show_portal_event_state_reset",
    "show_portal_manual_test_started",
    "show_portal_manual_test_stopped",
    "show_route_command_status",
    "show_screen_center_calibrated",
    "toggle_owned_dialog",
    "update_debug_overlay",
    "update_game_view_rect_item",
    "update_localization_view",
    "update_monitor_rect_item",
    "update_player_marker",
    "warn_default_nav_config_missing",
    "warn_event_config_missing",
    "warn_event_system_missing",
    "warn_map_config_missing",
    "warn_nav_config_missing_map",
    "warn_auto_navigation_invalid_route",
    "warn_auto_navigation_unavailable",
    "warn_navigation_map_config_incomplete",
    "warn_navigation_missing_screen_center",
    "warn_overlay_map_config_incomplete",
    "warn_portal_manual_test_missing_screen_center",
    "warn_move_target_requires_localization",
    "warn_route_save_failed",
]
